### ISSUE TITLE
aarlo fails to start (since 2022.6?)

### ISSUE THREAD

**Issue by orandasoft** [twrecked/hass-aarlo#612]
I believe I am getting this error since upgrading to 2022.6, but I am not sure.

imap message read failed'int' object has no attribute 'decode'
2fa core retrieval failed

**Comment by Morronic** [comment]
Same issue here.

**Comment by suneworld** [comment]
Same problem here.

**Comment by vasqued2** [comment]
Same issue.  On  v2022.6.7

Can confirm that switching to PUSH 2fa works.

**Comment by vasqued2** [comment]
Dug a little deeper and the issue is in pyaarlo and seems linked to Yahoo email.  Here is a link w/ more details and solutions that have worked for some people:  https://github.com/twrecked/pyaarlo/issues/96
