### ISSUE TITLE
Configuration Check fails because of Aarlo

### ISSUE THREAD

**Issue by Beertje135** [twrecked/hass-aarlo#320]
Can't restart my Home Assistant because Aarlo trows an error.

When checking Config I get this error:
                          Platform error sensor.aarlo - cannot import name 'COMPONENT_ATTRIBUTION' from 'custom_components.aarlo' (/config/custom_components/aarlo/__init__.py)

Running lastest 115.5 but Aarlo is not working after latest Aarlo Update. The 2FA not working because I don't have option to add email verification. I wanted to wait for a fix but now I can't restart HomeAssistant.

**Comment by twrecked** [comment]
How are you checking the config?

I'm working fine with 115.6 and 0.7.0.beta.5.

**Comment by twrecked** [comment]
Can you paste your aarlo config here.

**Comment by Beertje135** [comment]
```
aarlo:
  username: !secret username_arlo_2
  password: !secret password_arlo
  refresh_devices_every: 2
  stream_timeout: 120
```

**Comment by Beertje135** [comment]
Sorry for late reply. I removed the integration and add-on. Then reinstalled and now the error is gone.
I think something was mixed up in the component_attribution ...

**Comment by Beertje135** [comment]
If nobody else is experiencing these error then the bug can be closed for me.
