### ISSUE TITLE
0.8.1.16 - AttributeError: 'NoneType' object has no attribute 'close' - IMAP

### ISSUE THREAD

**Issue by helpcomp** [twrecked/hass-aarlo#1056]
After upgrading to 0.8.1.16 I'm getting Failed To Set Up. I've removed my email and replaced with ____ for security. I'm using IMAP as the TFA. I've deleted and re-created the integration hoping that would fix the issue but it has not.

Reverting to 8.1.14.1 fixes the issue.

2025-02-15 09:35:35.145 ERROR (SyncWorker_1) [pyaarlo] imap message read failed'NoneType' object has no attribute 'check'
2025-02-15 09:35:35.147 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aarlo for _______@_____.___ for aarlo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 637, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aarlo/__init__.py", line 246, in async_setup_entry
    arlo = await hass.async_add_executor_job(login, hass, domain_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aarlo/__init__.py", line 408, in login
    arlo = PyArlo(**PyaarloCfg.create_options(hass, conf))
  File "/usr/local/lib/python3.13/site-packages/pyaarlo/__init__.py", line 179, in __init__
    self._be = ArloBackEnd(self)
               ~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyaarlo/backend.py", line 124, in __init__
    self._new_login()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyaarlo/backend.py", line 1382, in _new_login
    self._auth_state = self._new_auth_new_auth()
                       ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyaarlo/backend.py", line 1187, in _new_auth_new_auth
    self._new_tfa_stop()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyaarlo/backend.py", line 1118, in _new_tfa_stop
    self._auth_tfa_handler.stop()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyaarlo/tfa.py", line 162, in stop
    self._imap.close()
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by twrecked** [comment]
I'm an idiot. I pushed a duff pyaarlo release.

I'll fix it.

**Comment by twrecked** [comment]
Can you go back to 14.1 then try again. I deleted the broken release.

**Comment by helpcomp** [comment]
> Can you go back to 14.1 then try again. I deleted the broken release.

Yeah, works on 14.1. I'll stay on 14.1 for now. Thanks!
