### ISSUE TITLE
No more camera preview

### ISSUE THREAD

**Issue by jimjam25** [twrecked/hass-aarlo#372]
v0.7.0.1 - v0.7.0.5

I can view other sensor information like battery levels, how many cameras are present, recent activity, but I can no longer see footage from the last video that was recorded during a motion trigger event. 

`Dec 30 16:26:47 raspberrypi hass[9317]: 2020-12-30 16:26:47 ERROR (MainThread) [aiohttp.server] Error handling request
Dec 30 16:26:47 raspberrypi hass[9317]: Traceback (most recent call last):
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
Dec 30 16:26:47 raspberrypi hass[9317]:     resp = await task
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
Dec 30 16:26:47 raspberrypi hass[9317]:     resp = await handler(request)
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
Dec 30 16:26:47 raspberrypi hass[9317]:     return await handler(request)
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
Dec 30 16:26:47 raspberrypi hass[9317]:     return await handler(request)
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
Dec 30 16:26:47 raspberrypi hass[9317]:     return await handler(request)
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 129, in handle
Dec 30 16:26:47 raspberrypi hass[9317]:     result = await result
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/camera/__init__.py", line 502, in get
Dec 30 16:26:47 raspberrypi hass[9317]:     return await self.handle(request, camera)
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/camera/__init__.py", line 537, in handle
Dec 30 16:26:47 raspberrypi hass[9317]:     return await camera.handle_async_mjpeg_stream(request)
Dec 30 16:26:47 raspberrypi hass[9317]:   File "/home/homeassistant/.homeassistant/custom_components/aarlo/camera.py", line 439, in handle_async_mjpeg_stream
Dec 30 16:26:47 raspberrypi hass[9317]:     stream = CameraMjpeg(self._ffmpeg.binary)
Dec 30 16:26:47 raspberrypi hass[9317]: TypeError: __init__() missing 1 required positional argument: 'loop'`

**Comment by twrecked** [comment]
Crap. I fixed it for the newer release of Home Assistant. Can you go back to version 0.7.0.4? It only has this fix in it.

I'll investigate the versions.

**Comment by jimjam25** [comment]
"Last video recorded" view works in 0.7.0.4, thanks!

**Comment by jimjam25** [comment]
leaving open pending fix to latest release. Thanks again for all the work on this project!

**Comment by twrecked** [comment]
Which version of Home Assistant are you on?

**Comment by jimjam25** [comment]
I'm on 0.7.0.4 now.

**Comment by twrecked** [comment]
Sorry, I meant HA version, not Aarlo version. I'm on  2020.12.2

**Comment by jimjam25** [comment]
DOH, I should have known. I'm on: 20201001.2  (0.116.4)

**Comment by cob94440** [comment]
I do not know if it s the same but i ve a problem with the snapshot command. It doesnt update.
Latest ha and Arlo version

**Comment by twrecked** [comment]
@cob94440 I just noticed this comment, they aren't related. What is your aarlo config?
